# Generated by Django 5.2 on 2025-04-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DFM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('specialty', models.CharField(max_length=50)),
                ('experience', models.PositiveIntegerField(help_text='Experience in years')),
            ],
        ),
    ]
