# Generated by Django 5.2 on 2025-04-19 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DFM', '0002_doctor_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor_info',
        ),
    ]
